name: camera_desktop_example
description: Demonstrates how to use the camera_desktop plugin.
publish_to: 'none'

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  camera_desktop:
    path: ../
  camera_platform_interface: ^2.8.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.9
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_linux: ^1.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
