name: camera_desktop
description: >-
  A Flutter camera plugin for desktop platforms (Linux, macOS, Windows).
  Implements camera_platform_interface for easy integration
  with the standard camera package.
version: 1.0.0
homepage: https://github.com/hugocornellier/camera_desktop
repository: https://github.com/hugocornellier/camera_desktop
issue_tracker: https://github.com/hugocornellier/camera_desktop/issues

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  camera_platform_interface: ^2.7.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: camera
    platforms:
      ios:
        dartPluginClass: CameraDesktopDart
      android:
        dartPluginClass: CameraDesktopDart
      linux:
        dartPluginClass: CameraDesktopPlugin
        pluginClass: CameraDesktopPlugin
      macos:
        dartPluginClass: CameraDesktopPlugin
        pluginClass: CameraDesktopPlugin
      windows:
        dartPluginClass: CameraDesktopPlugin
        pluginClass: CameraDesktopPlugin
